<?php
declare(strict_types=1);

// RunescapeApis SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

RunescapeApisUtility::setRegistrar(function (RunescapeApisUtility $u): void {
    $u->clean = [RunescapeApisClean::class, 'call'];
    $u->done = [RunescapeApisDone::class, 'call'];
    $u->make_error = [RunescapeApisMakeError::class, 'call'];
    $u->feature_add = [RunescapeApisFeatureAdd::class, 'call'];
    $u->feature_hook = [RunescapeApisFeatureHook::class, 'call'];
    $u->feature_init = [RunescapeApisFeatureInit::class, 'call'];
    $u->fetcher = [RunescapeApisFetcher::class, 'call'];
    $u->make_fetch_def = [RunescapeApisMakeFetchDef::class, 'call'];
    $u->make_context = [RunescapeApisMakeContext::class, 'call'];
    $u->make_options = [RunescapeApisMakeOptions::class, 'call'];
    $u->make_request = [RunescapeApisMakeRequest::class, 'call'];
    $u->make_response = [RunescapeApisMakeResponse::class, 'call'];
    $u->make_result = [RunescapeApisMakeResult::class, 'call'];
    $u->make_point = [RunescapeApisMakePoint::class, 'call'];
    $u->make_spec = [RunescapeApisMakeSpec::class, 'call'];
    $u->make_url = [RunescapeApisMakeUrl::class, 'call'];
    $u->param = [RunescapeApisParam::class, 'call'];
    $u->prepare_auth = [RunescapeApisPrepareAuth::class, 'call'];
    $u->prepare_body = [RunescapeApisPrepareBody::class, 'call'];
    $u->prepare_headers = [RunescapeApisPrepareHeaders::class, 'call'];
    $u->prepare_method = [RunescapeApisPrepareMethod::class, 'call'];
    $u->prepare_params = [RunescapeApisPrepareParams::class, 'call'];
    $u->prepare_path = [RunescapeApisPreparePath::class, 'call'];
    $u->prepare_query = [RunescapeApisPrepareQuery::class, 'call'];
    $u->graphql_body = [RunescapeApisGraphql::class, 'body'];
    $u->graphql_errors = [RunescapeApisGraphql::class, 'errors'];
    $u->result_basic = [RunescapeApisResultBasic::class, 'call'];
    $u->result_body = [RunescapeApisResultBody::class, 'call'];
    $u->result_headers = [RunescapeApisResultHeaders::class, 'call'];
    $u->transform_request = [RunescapeApisTransformRequest::class, 'call'];
    $u->transform_response = [RunescapeApisTransformResponse::class, 'call'];
});
